services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  validation:
    build:
      context: .
      dockerfile:
        "Dockerfile-Validator"
      args:
        platform: "linux/x86_64"
    command: node app.js
    # ports:
    #   - "3000:3000"
    volumes:
      - ./validation:/validation
  miladychan:
    build: 
      context: .
      dockerfile:
        "Dockerfile-Live"
      args:
        platform: "linux/x86_64"
      
    command: tail -f /dev/null
    entrypoint: "/meguca/scripts/with_postgres.sh"
    # ports:
    #   - "8000:8000"
    volumes:
      - .:/meguca