// Code generated by qtc from "auth.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line auth.html:1
package templates

//line auth.html:1
import "fmt"

//line auth.html:2
import "time"

//line auth.html:3
import "strconv"

//line auth.html:4
import "github.com/bakape/meguca/auth"

//line auth.html:5
import "github.com/bakape/meguca/config"

//line auth.html:6
import "github.com/bakape/meguca/lang"

//line auth.html:7
import "github.com/bakape/meguca/common"

//line auth.html:8
import "github.com/bakape/mnemonics"

// Header of a standalone HTML page

//line auth.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line auth.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line auth.html:11
func streamhtmlHeader(qw422016 *qt422016.Writer) {
//line auth.html:11
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="utf-8"/></head><body>`)
//line auth.html:18
}

//line auth.html:18
func writehtmlHeader(qq422016 qtio422016.Writer) {
//line auth.html:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:18
	streamhtmlHeader(qw422016)
//line auth.html:18
	qt422016.ReleaseWriter(qw422016)
//line auth.html:18
}

//line auth.html:18
func htmlHeader() string {
//line auth.html:18
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:18
	writehtmlHeader(qb422016)
//line auth.html:18
	qs422016 := string(qb422016.B)
//line auth.html:18
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:18
	return qs422016
//line auth.html:18
}

// End of a standalone HTML page

//line auth.html:21
func streamhtmlEnd(qw422016 *qt422016.Writer) {
//line auth.html:21
	qw422016.N().S(`</body></html>`)
//line auth.html:24
}

//line auth.html:24
func writehtmlEnd(qq422016 qtio422016.Writer) {
//line auth.html:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:24
	streamhtmlEnd(qw422016)
//line auth.html:24
	qt422016.ReleaseWriter(qw422016)
//line auth.html:24
}

//line auth.html:24
func htmlEnd() string {
//line auth.html:24
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:24
	writehtmlEnd(qb422016)
//line auth.html:24
	qs422016 := string(qb422016.B)
//line auth.html:24
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:24
	return qs422016
//line auth.html:24
}

// BanPage renders a ban page for a banned user

//line auth.html:27
func StreamBanPage(qw422016 *qt422016.Writer, rec auth.BanRecord) {
//line auth.html:28
	streamhtmlHeader(qw422016)
//line auth.html:29
	ln := lang.Get().Templates["banPage"]

//line auth.html:30
	if len(ln) < 2 {
//line auth.html:31
		panic(fmt.Errorf("invalid ban format strings: %v", ln))

//line auth.html:32
	}
//line auth.html:32
	qw422016.N().S(`<div class="ban-page glass">`)
//line auth.html:34
	qw422016.N().S(fmt.Sprintf(ln[0], bold(rec.Board), bold(rec.By)))
//line auth.html:34
	qw422016.N().S(`<br><br><b>`)
//line auth.html:38
	qw422016.E().S(rec.Reason)
//line auth.html:38
	qw422016.N().S(`</b><br><br>`)
//line auth.html:42
	exp := rec.Expires.Round(time.Second)

//line auth.html:43
	date := exp.Format(time.UnixDate)

//line auth.html:44
	till := exp.Sub(time.Now().Round(time.Second)).String()

//line auth.html:45
	qw422016.N().S(fmt.Sprintf(ln[1], bold(date), bold(till)))
//line auth.html:45
	qw422016.N().S(`<br><br><br></div>`)
//line auth.html:50
	streamhtmlEnd(qw422016)
//line auth.html:51
}

//line auth.html:51
func WriteBanPage(qq422016 qtio422016.Writer, rec auth.BanRecord) {
//line auth.html:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:51
	StreamBanPage(qw422016, rec)
//line auth.html:51
	qt422016.ReleaseWriter(qw422016)
//line auth.html:51
}

//line auth.html:51
func BanPage(rec auth.BanRecord) string {
//line auth.html:51
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:51
	WriteBanPage(qb422016, rec)
//line auth.html:51
	qs422016 := string(qb422016.B)
//line auth.html:51
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:51
	return qs422016
//line auth.html:51
}

// Renders a list of bans for a specific page with optional unbanning API links

//line auth.html:54
func StreamBanList(qw422016 *qt422016.Writer, bans []auth.BanRecord, board string, canUnban bool) {
//line auth.html:55
	streamhtmlHeader(qw422016)
//line auth.html:56
	streamtableStyle(qw422016)
//line auth.html:57
	ln := lang.Get()

//line auth.html:57
	qw422016.N().S(`<form method="post" action="/api/unban/`)
//line auth.html:58
	qw422016.N().S(board)
//line auth.html:58
	qw422016.N().S(`"><table>`)
//line auth.html:60
	headers := []string{
		"reason", "by", "post", "posterID", "expires", "type",
	}

//line auth.html:63
	if canUnban {
//line auth.html:64
		headers = append(headers, "unban")

//line auth.html:65
	}
//line auth.html:66
	streamtableHeaders(qw422016, headers...)
//line auth.html:67
	salt := config.Get().Salt

//line auth.html:68
	for _, b := range bans {
//line auth.html:68
		qw422016.N().S(`<tr><td>`)
//line auth.html:70
		qw422016.E().S(b.Reason)
//line auth.html:70
		qw422016.N().S(`</td><td>`)
//line auth.html:71
		qw422016.E().S(b.By)
//line auth.html:71
		qw422016.N().S(`</td><td>`)
//line auth.html:72
		streamstaticPostLink(qw422016, b.ForPost)
//line auth.html:72
		qw422016.N().S(`</td>`)
//line auth.html:73
		buf := make([]byte, 0, len(salt)+len(b.IP))

//line auth.html:74
		buf = append(buf, salt...)

//line auth.html:75
		buf = append(buf, b.IP...)

//line auth.html:75
		qw422016.N().S(`<td>`)
//line auth.html:76
		qw422016.E().S(mnemonic.FantasyName(buf))
//line auth.html:76
		qw422016.N().S(`</td><td>`)
//line auth.html:77
		qw422016.E().S(b.Expires.Format(time.UnixDate))
//line auth.html:77
		qw422016.N().S(`</td><td>`)
//line auth.html:78
		qw422016.E().S(ln.UI[b.Type])
//line auth.html:78
		qw422016.N().S(`</td>`)
//line auth.html:79
		if canUnban {
//line auth.html:79
			qw422016.N().S(`<td><input type="checkbox" name="`)
//line auth.html:81
			qw422016.E().S(strconv.FormatUint(b.ForPost, 10))
//line auth.html:81
			qw422016.N().S(`"></td>`)
//line auth.html:83
		}
//line auth.html:83
		qw422016.N().S(`</tr>`)
//line auth.html:85
	}
//line auth.html:85
	qw422016.N().S(`</table>`)
//line auth.html:87
	if canUnban {
//line auth.html:88
		streamsubmit(qw422016, false)
//line auth.html:89
	}
//line auth.html:89
	qw422016.N().S(`</form>`)
//line auth.html:91
	streamhtmlEnd(qw422016)
//line auth.html:92
}

//line auth.html:92
func WriteBanList(qq422016 qtio422016.Writer, bans []auth.BanRecord, board string, canUnban bool) {
//line auth.html:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:92
	StreamBanList(qw422016, bans, board, canUnban)
//line auth.html:92
	qt422016.ReleaseWriter(qw422016)
//line auth.html:92
}

//line auth.html:92
func BanList(bans []auth.BanRecord, board string, canUnban bool) string {
//line auth.html:92
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:92
	WriteBanList(qb422016, bans, board, canUnban)
//line auth.html:92
	qs422016 := string(qb422016.B)
//line auth.html:92
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:92
	return qs422016
//line auth.html:92
}

// Common style for plain html tables

//line auth.html:95
func streamtableStyle(qw422016 *qt422016.Writer) {
//line auth.html:95
	qw422016.N().S(`<style>table, th, td {border: 1px solid black;}.hash-link {display: none;}</style>`)
//line auth.html:104
}

//line auth.html:104
func writetableStyle(qq422016 qtio422016.Writer) {
//line auth.html:104
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:104
	streamtableStyle(qw422016)
//line auth.html:104
	qt422016.ReleaseWriter(qw422016)
//line auth.html:104
}

//line auth.html:104
func tableStyle() string {
//line auth.html:104
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:104
	writetableStyle(qb422016)
//line auth.html:104
	qs422016 := string(qb422016.B)
//line auth.html:104
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:104
	return qs422016
//line auth.html:104
}

// Post link, that will redirect to the post from any page

//line auth.html:107
func streamstaticPostLink(qw422016 *qt422016.Writer, id uint64) {
//line auth.html:108
	streampostLink(qw422016, common.Link{id, id, "all"}, true, true)
//line auth.html:109
}

//line auth.html:109
func writestaticPostLink(qq422016 qtio422016.Writer, id uint64) {
//line auth.html:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:109
	streamstaticPostLink(qw422016, id)
//line auth.html:109
	qt422016.ReleaseWriter(qw422016)
//line auth.html:109
}

//line auth.html:109
func staticPostLink(id uint64) string {
//line auth.html:109
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:109
	writestaticPostLink(qb422016, id)
//line auth.html:109
	qs422016 := string(qb422016.B)
//line auth.html:109
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:109
	return qs422016
//line auth.html:109
}

// Renders a moderation log page

//line auth.html:112
func StreamModLog(qw422016 *qt422016.Writer, log []auth.ModLogEntry) {
//line auth.html:113
	streamhtmlHeader(qw422016)
//line auth.html:114
	ln := lang.Get()

//line auth.html:115
	streamtableStyle(qw422016)
//line auth.html:115
	qw422016.N().S(`<table>`)
//line auth.html:117
	streamtableHeaders(qw422016, "type", "by", "post", "time", "data", "duration")
//line auth.html:118
	for _, l := range log {
//line auth.html:118
		qw422016.N().S(`<tr><td>`)
//line auth.html:121
		switch l.Type {
//line auth.html:122
		case common.BanPost:
//line auth.html:123
			qw422016.E().S(ln.UI["ban"])
//line auth.html:124
		case common.ShadowBinPost:
//line auth.html:125
			qw422016.E().S(ln.UI["shadowBin"])
//line auth.html:126
		case common.UnbanPost:
//line auth.html:127
			qw422016.E().S(ln.UI["unban"])
//line auth.html:128
		case common.DeletePost:
//line auth.html:129
			qw422016.E().S(ln.UI["deletePost"])
//line auth.html:130
		case common.DeleteImage:
//line auth.html:131
			qw422016.E().S(ln.UI["deleteImage"])
//line auth.html:132
		case common.SpoilerImage:
//line auth.html:133
			qw422016.E().S(ln.UI["spoilerImage"])
//line auth.html:134
		case common.LockThread:
//line auth.html:135
			qw422016.E().S(ln.Common.UI["lockThread"])
//line auth.html:136
		case common.DeleteBoard:
//line auth.html:137
			qw422016.E().S(ln.Common.UI["deleteBoard"])
//line auth.html:138
		case common.MeidoVision:
//line auth.html:139
			qw422016.E().S(ln.Common.UI["meidoVisionPost"])
//line auth.html:140
		case common.PurgePost:
//line auth.html:141
			qw422016.E().S(ln.UI["purgePost"])
//line auth.html:142
		}
//line auth.html:142
		qw422016.N().S(`</td><td>`)
//line auth.html:144
		qw422016.E().S(l.By)
//line auth.html:144
		qw422016.N().S(`</td><td>`)
//line auth.html:146
		if l.ID != 0 {
//line auth.html:147
			streamstaticPostLink(qw422016, l.ID)
//line auth.html:148
		}
//line auth.html:148
		qw422016.N().S(`</td><td>`)
//line auth.html:150
		qw422016.E().S(l.Created.Format(time.UnixDate))
//line auth.html:150
		qw422016.N().S(`</td><td>`)
//line auth.html:151
		qw422016.E().S(l.Data)
//line auth.html:151
		qw422016.N().S(`</td><td>`)
//line auth.html:153
		if l.Length != 0 {
//line auth.html:154
			qw422016.E().S((time.Second * time.Duration(l.Length)).String())
//line auth.html:155
		}
//line auth.html:155
		qw422016.N().S(`</td></tr>`)
//line auth.html:158
	}
//line auth.html:158
	qw422016.N().S(`</table>`)
//line auth.html:160
	streamhtmlEnd(qw422016)
//line auth.html:161
}

//line auth.html:161
func WriteModLog(qq422016 qtio422016.Writer, log []auth.ModLogEntry) {
//line auth.html:161
	qw422016 := qt422016.AcquireWriter(qq422016)
//line auth.html:161
	StreamModLog(qw422016, log)
//line auth.html:161
	qt422016.ReleaseWriter(qw422016)
//line auth.html:161
}

//line auth.html:161
func ModLog(log []auth.ModLogEntry) string {
//line auth.html:161
	qb422016 := qt422016.AcquireByteBuffer()
//line auth.html:161
	WriteModLog(qb422016, log)
//line auth.html:161
	qs422016 := string(qb422016.B)
//line auth.html:161
	qt422016.ReleaseByteBuffer(qb422016)
//line auth.html:161
	return qs422016
//line auth.html:161
}
